# задание 2
num1 = float(input('Введите первое число:'))
num2 = float(input('Введите второе число:'))
print(num1 + num2) 
print(num1 - num2)  
print(num1 * num2) 
print(num1 / num2) 
print(num1 // num2) 
print(num1 % num2) 
print(num1 ** num2) 